# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "gton/page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Dan Cunnington

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Dan Cunnington

description: Stylish Jekyll Theme
author:
  name: dancunnington
  email: dancunnington@hotmail.co.uk
  github: dancunnington
  twitter: dancunnington
  linkedin: dan-cunnington-94b0127b
  bio: Runner and Computer Scientist. Born in Northumberland, a University of Sheffield graduate and currently developing software for IBM Emerging Technology.
  email_md5: c0857ace6100aad81df7bcff29aca42c

rss_path: feed.xml
tags_path: tags.html
categories_path: categories.html

# set it as url of an image
#sidebar_background_image: assets/media/bg.JPG

url: http://dancunnington.github.io/

BASE_PATH:

gems:
  - jekyll-paginate